name: "Build"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                include:
                    - os: ubuntu-latest
                      packages: "build-essential"
                    - os: macos-latest
                      packages: ""

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get update && sudo apt-get install -y ${{ matrix.packages }}

            - name: Build project
              run: make
